name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
      - run: npm i -g yarn
      - run: yarn install --use-lockfile
      - name: Run eslint
      - run: yarn lint
