name: Test

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn --use-lockfile
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: yarn test
